### PR TITLE
Code Challenge Project

### PR DESCRIPTION
**Pull request by matheusmb**

### CODE REVIEW

**Comment by arctouch-ismaelstahelin** [comment]
Hi Matheus, thanks for applying. 
Can you give me a new PR with just the revelant code changes excluding things like bootstrap code, composer modules code or anything that is not yours?
Thanks!

**Comment by arctouch-ismaelstahelin** [comment]
I wasn't able to run the project using docker following the instructions you provided. Any additional instructions?

**Comment by matheusmb** [comment]
Hello @arctouch-ismaelstahelin, I created another PR as requested. You can check it here: https://github.com/matheusmb/arctouch-codechallenge/pull/2

**Comment by matheusmb** [comment]
@arctouch-ismaelstahelin regarding the docker, I suspect that I forgot to include the html folder in the cmd line. The correct command should be:
`$ docker run -d -u 999:0 -p ${PORT}:8080 -v ${PROJECT_DIR}:/var/www/html/ 1and1internet/ubuntu-16-apache-php-5.6`

As alternative, I created an image which already includes the project files. You can execute by
`$ docker run -d -p 8080:8080 matheusmb/arctouch_challenge`

The project should be available accessing http://localhost:8080

Thanks for your attention.

**Pull request closed without merging**
